baseURL = "www.thesudo.group"
languageCode = "en-us"
title = "Hugo Hero Theme"
themesDir = "../.."
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "TheSudoGroup is a cybersecurity & digital services firm located in New York City."
    meta_og_title = "TheSudoGroup"
    meta_og_type = "website"

    meta_og_url = "https://thesudo.group"
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
